# Use root/example as user/password credentials
version: '3.1'

services:
  arangodb:
    image: arangodb
    volumes:
      - arangodb:/var/lib/arangodb3
    ports:
      - 8529:8529
    environment:
      ARANGO_ROOT_PASSWORD: abc123

  parser:
    image: nsr-parser
    environment:
      ARANGODB_HOST: http://arangodb:8529
      ARANGODB_USER: root
      ARANGODB_PASSWORD: abc123

volumes:
  arangodb:
