// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.7
// source: trainroute/protos/trainroute.proto

package trainroute

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trainroute_protos_trainroute_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_trainroute_protos_trainroute_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_trainroute_protos_trainroute_proto_rawDescGZIP(), []int{0}
}

type OtrId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrainId string `protobuf:"bytes,1,opt,name=train_id,json=trainId,proto3" json:"train_id,omitempty"`
}

func (x *OtrId) Reset() {
	*x = OtrId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trainroute_protos_trainroute_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OtrId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtrId) ProtoMessage() {}

func (x *OtrId) ProtoReflect() protoreflect.Message {
	mi := &file_trainroute_protos_trainroute_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtrId.ProtoReflect.Descriptor instead.
func (*OtrId) Descriptor() ([]byte, []int) {
	return file_trainroute_protos_trainroute_proto_rawDescGZIP(), []int{1}
}

func (x *OtrId) GetTrainId() string {
	if x != nil {
		return x.TrainId
	}
	return ""
}

type OtrIdList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrainIds []*OtrId `protobuf:"bytes,1,rep,name=train_ids,json=trainIds,proto3" json:"train_ids,omitempty"`
}

func (x *OtrIdList) Reset() {
	*x = OtrIdList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trainroute_protos_trainroute_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OtrIdList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtrIdList) ProtoMessage() {}

func (x *OtrIdList) ProtoReflect() protoreflect.Message {
	mi := &file_trainroute_protos_trainroute_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtrIdList.ProtoReflect.Descriptor instead.
func (*OtrIdList) Descriptor() ([]byte, []int) {
	return file_trainroute_protos_trainroute_proto_rawDescGZIP(), []int{2}
}

func (x *OtrIdList) GetTrainIds() []*OtrId {
	if x != nil {
		return x.TrainIds
	}
	return nil
}

type OperatingTrainRoute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrainId   string                 `protobuf:"bytes,1,opt,name=train_id,json=trainId,proto3" json:"train_id,omitempty"`
	TrainDate *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=train_date,json=trainDate,proto3" json:"train_date,omitempty"`
}

func (x *OperatingTrainRoute) Reset() {
	*x = OperatingTrainRoute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trainroute_protos_trainroute_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperatingTrainRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatingTrainRoute) ProtoMessage() {}

func (x *OperatingTrainRoute) ProtoReflect() protoreflect.Message {
	mi := &file_trainroute_protos_trainroute_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatingTrainRoute.ProtoReflect.Descriptor instead.
func (*OperatingTrainRoute) Descriptor() ([]byte, []int) {
	return file_trainroute_protos_trainroute_proto_rawDescGZIP(), []int{3}
}

func (x *OperatingTrainRoute) GetTrainId() string {
	if x != nil {
		return x.TrainId
	}
	return ""
}

func (x *OperatingTrainRoute) GetTrainDate() *timestamppb.Timestamp {
	if x != nil {
		return x.TrainDate
	}
	return nil
}

type OperatingTrainRouteList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Routes []*OperatingTrainRoute `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
}

func (x *OperatingTrainRouteList) Reset() {
	*x = OperatingTrainRouteList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trainroute_protos_trainroute_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperatingTrainRouteList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatingTrainRouteList) ProtoMessage() {}

func (x *OperatingTrainRouteList) ProtoReflect() protoreflect.Message {
	mi := &file_trainroute_protos_trainroute_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatingTrainRouteList.ProtoReflect.Descriptor instead.
func (*OperatingTrainRouteList) Descriptor() ([]byte, []int) {
	return file_trainroute_protos_trainroute_proto_rawDescGZIP(), []int{4}
}

func (x *OperatingTrainRouteList) GetRoutes() []*OperatingTrainRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

var File_trainroute_protos_trainroute_proto protoreflect.FileDescriptor

var file_trainroute_protos_trainroute_proto_rawDesc = []byte{
	0x0a, 0x22, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2f, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x22,
	0x0a, 0x05, 0x4f, 0x74, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x69, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x69, 0x6e,
	0x49, 0x64, 0x22, 0x30, 0x0a, 0x09, 0x4f, 0x74, 0x72, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x23, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x06, 0x2e, 0x4f, 0x74, 0x72, 0x49, 0x64, 0x52, 0x08, 0x74, 0x72, 0x61, 0x69,
	0x6e, 0x49, 0x64, 0x73, 0x22, 0x6b, 0x0a, 0x13, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x74,
	0x72, 0x61, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74,
	0x72, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x5f,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x44, 0x61, 0x74,
	0x65, 0x22, 0x47, 0x0a, 0x17, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x72,
	0x61, 0x69, 0x6e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x06,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x52, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x32, 0x73, 0x0a, 0x1a, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x09, 0x46, 0x75, 0x6c, 0x6c,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0a, 0x2e,
	0x4f, 0x74, 0x72, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x08, 0x47,
	0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x0a, 0x2e, 0x4f, 0x74, 0x72, 0x49, 0x64, 0x4c,
	0x69, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x54,
	0x72, 0x61, 0x69, 0x6e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x42,
	0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x65,
	0x6e, 0x67, 0x6c, 0x61, 0x2f, 0x6e, 0x73, 0x72, 0x2d, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2f,
	0x74, 0x72, 0x61, 0x69, 0x6e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_trainroute_protos_trainroute_proto_rawDescOnce sync.Once
	file_trainroute_protos_trainroute_proto_rawDescData = file_trainroute_protos_trainroute_proto_rawDesc
)

func file_trainroute_protos_trainroute_proto_rawDescGZIP() []byte {
	file_trainroute_protos_trainroute_proto_rawDescOnce.Do(func() {
		file_trainroute_protos_trainroute_proto_rawDescData = protoimpl.X.CompressGZIP(file_trainroute_protos_trainroute_proto_rawDescData)
	})
	return file_trainroute_protos_trainroute_proto_rawDescData
}

var file_trainroute_protos_trainroute_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_trainroute_protos_trainroute_proto_goTypes = []interface{}{
	(*Empty)(nil),                   // 0: Empty
	(*OtrId)(nil),                   // 1: OtrId
	(*OtrIdList)(nil),               // 2: OtrIdList
	(*OperatingTrainRoute)(nil),     // 3: OperatingTrainRoute
	(*OperatingTrainRouteList)(nil), // 4: OperatingTrainRouteList
	(*timestamppb.Timestamp)(nil),   // 5: google.protobuf.Timestamp
}
var file_trainroute_protos_trainroute_proto_depIdxs = []int32{
	1, // 0: OtrIdList.train_ids:type_name -> OtrId
	5, // 1: OperatingTrainRoute.train_date:type_name -> google.protobuf.Timestamp
	3, // 2: OperatingTrainRouteList.routes:type_name -> OperatingTrainRoute
	0, // 3: OperatingTrainRouteService.FullState:input_type -> Empty
	2, // 4: OperatingTrainRouteService.GetItems:input_type -> OtrIdList
	2, // 5: OperatingTrainRouteService.FullState:output_type -> OtrIdList
	4, // 6: OperatingTrainRouteService.GetItems:output_type -> OperatingTrainRouteList
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_trainroute_protos_trainroute_proto_init() }
func file_trainroute_protos_trainroute_proto_init() {
	if File_trainroute_protos_trainroute_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_trainroute_protos_trainroute_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trainroute_protos_trainroute_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OtrId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trainroute_protos_trainroute_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OtrIdList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trainroute_protos_trainroute_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperatingTrainRoute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trainroute_protos_trainroute_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperatingTrainRouteList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_trainroute_protos_trainroute_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trainroute_protos_trainroute_proto_goTypes,
		DependencyIndexes: file_trainroute_protos_trainroute_proto_depIdxs,
		MessageInfos:      file_trainroute_protos_trainroute_proto_msgTypes,
	}.Build()
	File_trainroute_protos_trainroute_proto = out.File
	file_trainroute_protos_trainroute_proto_rawDesc = nil
	file_trainroute_protos_trainroute_proto_goTypes = nil
	file_trainroute_protos_trainroute_proto_depIdxs = nil
}
